version: "3"

services:
  jupyter:
    container_name: decode-bufr-jupyter
    build:
      context: .
    ports:
      - 80:8888
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    volumes:
      - ./notebooks:/root/notebooks:rw
