version: "3"

services:
  jupyter:
    container_name: decode-bufr-jupyter
    build:
      context: .
    ports:
      - 8888:8888
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    volumes:
      - ./notebooks:/root/notebooks:rw
      - ./sample-data:/root/sample-data:ro